import { createContext, useContext, useState, ReactNode } from "react";

export type LanguageCode = 
  | "tr" | "en" | "zh" | "hi" | "es" | "ar" | "bn" | "pt" 
  | "ru" | "ja" | "de" | "fr" | "ko" | "it" | "vi";

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  currentLanguage: Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("language");
    return (saved as LanguageCode) || "tr";
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Turkish translations - base language
const trTranslations: Record<string, string> = {
  // Navigation
  "nav.home": "Ana Sayfa",
  "nav.vehicles": "Araçlar",
  "nav.reviews": "İncelemeler",
  "nav.compare": "Karşılaştır",
  "nav.communities": "Topluluklar",
  "nav.finance": "Finans",
  
  // Auth
  "auth.login": "Giriş Yap",
  "auth.logout": "Çıkış Yap",
  "auth.profile": "Profilim",
  "auth.user": "Kullanıcı",
  "auth.welcome": "Hoş Geldiniz",
  "auth.createAccount": "Hesap Oluşturun",
  "auth.loginDesc": "Hesabınıza giriş yaparak devam edin",
  "auth.signupDesc": "Yorum yazmak ve favorilerinizi kaydetmek için kayıt olun",
  "auth.googleLogin": "Google ile Giriş Yap",
  "auth.googleSignup": "Google ile Kayıt Ol",
  "auth.or": "veya",
  "auth.email": "E-posta",
  "auth.password": "Şifre",
  "auth.confirmPassword": "Şifre Tekrar",
  "auth.signup": "Kayıt Ol",
  "auth.noAccount": "Hesabınız yok mu?",
  "auth.hasAccount": "Zaten hesabınız var mı?",
  "auth.backToHome": "Ana Sayfaya Dön",
  "auth.shareExperience": "Araç Deneyimlerinizi Paylaşın",
  "auth.shareDesc": "Binlerce kullanıcıyla birlikte gerçek araç yorumları yazın, favorilerinizi kaydedin ve toplulukla etkileşime geçin.",
  
  // Premium
  "premium.badge": "Premium",
  "premium.button": "Be Premium",
  "premium.member": "Premium Üye",
  
  // Search
  "search.placeholder": "Araç markası veya model ara...",
  "search.title": "Site İçi Arama",
  "search.hint": "Araç markası veya model yazarak arama yapın",
  "search.noResults": "için sonuç bulunamadı",
  "search.mobile": "Araç Ara...",
  "search.searchBrandModel": "Marka, model veya kategori ara...",
  "search.button": "Ara",
  
  // Hero Section
  "hero.badge": "Dünyanın En Kapsamlı Üst Segment ve Lüks Araç Platformu",
  "hero.title": "Premium Araçları",
  "hero.titleHighlight": "Keşfedin",
  "hero.subtitle": "2022-2026 model üst segment ve lüks araçların detaylı incelemeleri, gerçek kullanıcı yorumları ve karşılaştırmaları.",
  
  // Stats
  "stats.vehicles": "Araç Modeli",
  "stats.reviews": "Kullanıcı Yorumu",
  "stats.brands": "Marka",
  
  // Sections
  "section.popularBrands": "Popüler Markalar",
  "section.viewAll": "Tümünü Gör",
  "section.categories": "Kategoriler",
  "section.popularVehicles": "Popüler Araçlar",
  "section.popularVehiclesDesc": "En çok incelenen ve beğenilen modeller",
  "section.latestReviews": "Son Yorumlar",
  "section.latestReviewsDesc": "Kullanıcılardan gelen en son değerlendirmeler",
  "section.readMore": "Devamını oku →",
  
  // CTA Section
  "cta.title": "Deneyimlerinizi Paylaşın",
  "cta.subtitle": "Aracınız hakkında yorum yaparak diğer kullanıcılara yardımcı olun ve topluluğumuza katılın.",
  "cta.button": "Yorum Yaz",
  
  // Review Dialog
  "review.writeTitle": "Yorum Yazmak İster misiniz?",
  "review.writeDesc": "Deneyimlerinizi paylaşmak için önce bir araç seçmeniz gerekiyor. Araç listesinden yorum yapmak istediğiniz aracı seçebilirsiniz.",
  "review.goToList": "Araç Listesine Git",
  "review.hint": "Araç detay sayfasında \"Yorum Yaz\" butonuna tıklayarak deneyiminizi paylaşabilirsiniz.",
  "review.pros": "Artıları",
  "review.cons": "Eksileri",
  "review.helpful": "Faydalı",
  "review.viewVehicle": "Aracı İncele",
  "review.reviews": "yorum",
  
  // Vehicle Card & Detail
  "vehicle.startingPrice": "Başlangıç Fiyatı",
  "vehicle.review": "yorum",
  "vehicle.reviews": "yorum",
  "vehicle.notFound": "Araç bulunamadı",
  "vehicle.backToVehicles": "Araçlara Dön",
  "vehicle.model": "Model",
  "vehicle.evaluation": "değerlendirme",
  "vehicle.writeReview": "Yorum Yaz",
  "vehicle.specs": "Özellikler",
  "vehicle.reviews.tab": "Yorumlar",
  "vehicle.overview": "Genel Bakış",
  "vehicle.featuredFeatures": "Öne Çıkan Özellikler",
  "vehicle.technicalSpecs": "Teknik Özellikler",
  "vehicle.userReviews": "Kullanıcı Yorumları",
  "vehicle.noReviews": "Henüz yorum yapılmamış. İlk yorumu siz yapın!",
  "vehicle.writeFirstReview": "İlk Yorumu Yaz",
  "vehicle.reviewStats": "Yorum İstatistikleri",
  "vehicle.totalReviews": "Toplam Yorum",
  "vehicle.averageRating": "Ortalama Puan",
  "vehicle.loginToReview": "Yorum yapmak için giriş yapın",
  "vehicle.similarVehicles": "Benzer Araçlar",
  "vehicle.financeTitle": "Kredi Seçeneklerini İncele",
  "vehicle.financeDesc": "En uygun araç kredisi tekliflerini karşılaştır",
  "vehicle.loanCalculator": "Kredi Hesaplama",
  "vehicle.downPayment": "Peşinat",
  "vehicle.term": "Vade",
  "vehicle.monthlyPayment": "Aylık Taksit",
  "vehicle.loanAmount": "Kredi Tutarı",
  "vehicle.totalInterest": "Toplam Faiz",
  "vehicle.compareLoans": "Tüm Kredi Tekliflerini Karşılaştır",
  "vehicle.bankComparison": "Banka Karşılaştırması",
  "vehicle.bestRate": "En Uygun",
  "vehicle.annualRate": "yıllık faiz",
  "vehicle.totalInterestShort": "Faiz:",
  "vehicle.savingsRange": "Tasarruf Farkı",
  
  // Finance
  "finance.badge": "Araç Finansmanı",
  "finance.title": "En Uygun",
  "finance.titleHighlight": "Araç Kredisi",
  "finance.subtitle": "Türkiye'nin önde gelen bankalarının araç kredisi tekliflerini karşılaştırın, en uygun faiz oranlarını keşfedin.",
  "finance.banks": "Banka",
  "finance.minRate": "En Düşük Faiz",
  "finance.maxTerm": "Ay Vade",
  "finance.maxAmount": "TL'ye Kadar",
  "finance.calculator": "Kredi Hesaplama",
  "finance.loanAmount": "Kredi Tutarı",
  "finance.loanTerm": "Vade",
  "finance.months": "Ay",
  "finance.loanType": "Kredi Türü",
  "finance.allTypes": "Tüm Krediler",
  "finance.vehicleLoan": "Araç Kredisi",
  "finance.consumerLoan": "İhtiyaç Kredisi",
  "finance.searchBank": "Banka ara...",
  "finance.sortByRate": "En Düşük Faiz",
  "finance.sortByRating": "En Yüksek Puan",
  "finance.sortByAmount": "En Yüksek Limit",
  "finance.interestRate": "Faiz Oranı",
  "finance.monthlyPayment": "Aylık Taksit",
  "finance.totalInterest": "Toplam Faiz",
  "finance.totalPayment": "Toplam Ödeme",
  "finance.specialOffer": "Özel Teklif",
  "finance.apply": "Başvur",
  "finance.noResults": "Aradığınız kriterlere uygun kredi bulunamadı.",
  "finance.lowRates": "Düşük Faiz Oranları",
  "finance.lowRatesDesc": "Piyasadaki en uygun faiz oranlarını karşılaştırarak bütçenize en uygun seçeneği bulun.",
  "finance.flexibleTerms": "Esnek Vade Seçenekleri",
  "finance.flexibleTermsDesc": "12 aydan 60 aya kadar esnek vade seçenekleriyle ödeme planınızı kendiniz belirleyin.",
  "finance.secure": "Güvenli Başvuru",
  "finance.secureDesc": "Tüm bankalar BDDK lisanslıdır. Bilgileriniz güvenle korunur.",
  // Specs
  "specs.engine": "Motor",
  "specs.power": "Güç",
  "specs.fuel": "Yakıt",
  "specs.fuelType": "Yakıt Tipi",
  "specs.transmission": "Şanzıman",
  "specs.acceleration": "Hızlanma",
  "specs.topSpeed": "Maksimum Hız",
  "specs.fuelConsumption": "Yakıt Tüketimi",
  "specs.bodyType": "Kasa Tipi",
  
  // Vehicle List Page
  "vehicleList.title": "Araç Kataloğu",
  "vehicleList.subtitle": "+ araç arasından size uygun olanı bulun",
  "vehicleList.filters": "Filtreler",
  "vehicleList.allBrands": "Tüm Markalar",
  "vehicleList.allCategories": "Tüm Kategoriler",
  "vehicleList.allYears": "Tüm Yıllar",
  "vehicleList.sortPopular": "En Popüler",
  "vehicleList.sortRating": "En Yüksek Puan",
  "vehicleList.sortReviews": "En Çok Yorum",
  "vehicleList.sortNewest": "En Yeni",
  "vehicleList.activeFilters": "Aktif Filtreler:",
  "vehicleList.clearAll": "Tümünü Temizle",
  "vehicleList.clearFilters": "Filtreleri Temizle",
  "vehicleList.found": "araç bulundu",
  "vehicleList.noResults": "Aradığınız kriterlere uygun araç bulunamadı.",
  "vehicleList.suggestVehicle": "Yeni Araç Öner",
  
  // Footer
  "footer.description": "Dünyanın en kapsamlı üst segment ve lüks araç inceleme ve yorum platformu. 2022-2026 model premium araçların gerçek kullanıcı deneyimleri.",
  "footer.quickLinks": "Hızlı Bağlantılar",
  "footer.allVehicles": "Tüm Araçlar",
  "footer.brands": "Markalar",
  "footer.compareVehicles": "Araç Karşılaştır",
  "footer.mostPopular": "En Popüler",
  "footer.newModels": "Yeni Modeller",
  "footer.categories": "Kategoriler",
  "footer.contact": "İletişim",
  "footer.rights": "Tüm hakları saklıdır.",
  "footer.privacy": "Gizlilik Politikası",
  "footer.terms": "Kullanım Koşulları",
  
  // Categories
  "category.sedan": "Sedan",
  "category.suv": "SUV",
  "category.hatchback": "Hatchback",
  "category.coupe": "Coupe",
  "category.pickup": "Pickup",
  "category.mpv": "MPV",
  
  // Common
  "common.year": "Yıl",
  "common.category": "Kategori",
  "common.price": "Fiyat",
  "common.rating": "Puan",
  "common.reviews": "Değerlendirme",
  "common.error": "Hata",
  "common.success": "Başarılı",
  "common.loading": "Yükleniyor...",
  
  // Profile
  "profile.loading": "Yükleniyor...",
  "profile.loginRequired": "Profil sayfasını görüntülemek için giriş yapmalısınız.",
  "profile.editProfile": "Profili Düzenle",
  "profile.logout": "Çıkış Yap",
  "profile.vehicleEnthusiast": "Araç Tutkunu",
  "profile.memberSince": "tarihinden beri üye",
  "profile.reviews": "Yorum",
  "profile.likes": "Beğeni",
  "profile.followers": "Takipçi",
  "profile.editTitle": "Profili Düzenle",
  "profile.editDesc": "Profil bilgilerinizi güncelleyin. Değişiklikler kaydedildikten sonra profilinizde görünecektir.",
  "profile.displayName": "Görünen Ad",
  "profile.displayNameHint": "Diğer kullanıcıların göreceği isminiz",
  "profile.displayNamePlaceholder": "Adınız Soyadınız",
  "profile.about": "Hakkında",
  "profile.aboutPlaceholder": "Kendinizi kısaca tanıtın...",
  "profile.aboutHint": "Maksimum 200 karakter",
  "profile.location": "Konum",
  "profile.locationPlaceholder": "Şehir, Ülke",
  "profile.locationHint": "Örn: İstanbul, Türkiye",
  "profile.cancel": "İptal",
  "profile.save": "Kaydet",
  "profile.myReviews": "Yorumlarım",
  "profile.favorites": "Favoriler",
  "profile.activity": "Aktivite",
  "profile.replies": "Yanıtlar",
  "profile.view": "Görüntüle",
  "profile.detailedStats": "Detaylı İstatistikler",
  "profile.totalReviews": "Toplam Yorum",
  "profile.thisMonth": "Bu ay",
  "profile.averageRating": "Ortalama Puan",
  "profile.totalLikes": "Toplam Beğeni",
  "profile.brandsExperienced": "Deneyimlediği Marka",
  "profile.diversity": "Çeşitlilik",
  "profile.achievements": "Başarılar",
  "profile.earned": "Kazanıldı",
  "profile.progress": "İlerleme",
  "profile.reviewCategories": "Yorum Kategorileri",
  "profile.brandDistribution": "Marka Dağılımı",
  "profile.ratingDistribution": "Puan Dağılımı",
  "profile.recentInteractions": "Son Etkileşimler",
  "profile.other": "Diğer",
  "profile.avatarSuccess": "Profil fotoğrafı başarıyla güncellendi!",
  "profile.avatarError": "Fotoğraf yüklenirken hata oluştu",
  "profile.profileSuccess": "Profil başarıyla güncellendi!",
  "profile.profileError": "Profil güncellenirken hata oluştu",
  "profile.fileTypeError": "Sadece JPG, PNG, WebP veya GIF formatları destekleniyor.",
  "profile.fileSizeError": "Dosya boyutu maksimum 5MB olabilir.",
};

// English translations
const enTranslations: Record<string, string> = {
  "nav.home": "Home",
  "nav.vehicles": "Vehicles",
  "nav.reviews": "Reviews",
  "nav.compare": "Compare",
  "nav.communities": "Communities",
  "nav.finance": "Finance",
  "auth.login": "Login",
  "auth.logout": "Logout",
  "auth.profile": "My Profile",
  "auth.user": "User",
  "auth.welcome": "Welcome",
  "auth.createAccount": "Create Account",
  "auth.loginDesc": "Sign in to continue to your account",
  "auth.signupDesc": "Register to write reviews and save favorites",
  "auth.googleLogin": "Login with Google",
  "auth.googleSignup": "Sign up with Google",
  "auth.or": "or",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.confirmPassword": "Confirm Password",
  "auth.signup": "Sign Up",
  "auth.noAccount": "Don't have an account?",
  "auth.hasAccount": "Already have an account?",
  "auth.backToHome": "Back to Home",
  "auth.shareExperience": "Share Your Vehicle Experience",
  "auth.shareDesc": "Write real vehicle reviews with thousands of users, save your favorites and interact with the community.",
  "premium.badge": "Premium",
  "premium.button": "Be Premium",
  "premium.member": "Premium Member",
  "search.placeholder": "Search brand or model...",
  "search.title": "Site Search",
  "search.hint": "Type brand or model to search",
  "search.noResults": "No results found for",
  "search.mobile": "Search...",
  "search.searchBrandModel": "Search brand, model or category...",
  "search.button": "Search",
  "hero.badge": "World's Most Comprehensive Premium & Luxury Car Platform",
  "hero.title": "Discover Premium",
  "hero.titleHighlight": "Vehicles",
  "hero.subtitle": "Detailed reviews, real user comments and comparisons of 2022-2026 premium and luxury vehicles.",
  "stats.vehicles": "Vehicle Models",
  "stats.reviews": "User Reviews",
  "stats.brands": "Brands",
  "section.popularBrands": "Popular Brands",
  "section.viewAll": "View All",
  "section.categories": "Categories",
  "section.popularVehicles": "Popular Vehicles",
  "section.popularVehiclesDesc": "Most reviewed and liked models",
  "section.latestReviews": "Latest Reviews",
  "section.latestReviewsDesc": "Latest reviews from users",
  "section.readMore": "Read more →",
  "cta.title": "Share Your Experience",
  "cta.subtitle": "Help other users by reviewing your vehicle and join our community.",
  "cta.button": "Write Review",
  "review.writeTitle": "Want to Write a Review?",
  "review.writeDesc": "To share your experience, you need to select a vehicle first. You can select the vehicle you want to review from the vehicle list.",
  "review.goToList": "Go to Vehicle List",
  "review.hint": "You can share your experience by clicking the \"Write Review\" button on the vehicle detail page.",
  "review.pros": "Pros",
  "review.cons": "Cons",
  "review.helpful": "Helpful",
  "review.viewVehicle": "View Vehicle",
  "review.reviews": "reviews",
  "vehicle.startingPrice": "Starting Price",
  "vehicle.review": "review",
  "vehicle.reviews": "reviews",
  "vehicle.notFound": "Vehicle not found",
  "vehicle.backToVehicles": "Back to Vehicles",
  "vehicle.model": "Model",
  "vehicle.evaluation": "reviews",
  "vehicle.writeReview": "Write Review",
  "vehicle.specs": "Specifications",
  "vehicle.reviews.tab": "Reviews",
  "vehicle.overview": "Overview",
  "vehicle.featuredFeatures": "Featured Features",
  "vehicle.technicalSpecs": "Technical Specifications",
  "vehicle.userReviews": "User Reviews",
  "vehicle.noReviews": "No reviews yet. Be the first to review!",
  "vehicle.writeFirstReview": "Write First Review",
  "vehicle.reviewStats": "Review Statistics",
  "vehicle.totalReviews": "Total Reviews",
  "vehicle.averageRating": "Average Rating",
  "vehicle.loginToReview": "Login to write a review",
  "vehicle.similarVehicles": "Similar Vehicles",
  "vehicle.financeTitle": "Explore Financing Options",
  "vehicle.financeDesc": "Compare the best car loan offers",
  "vehicle.loanCalculator": "Loan Calculator",
  "vehicle.downPayment": "Down Payment",
  "vehicle.term": "Term",
  "vehicle.monthlyPayment": "Monthly Payment",
  "vehicle.loanAmount": "Loan Amount",
  "vehicle.totalInterest": "Total Interest",
  "vehicle.compareLoans": "Compare All Loan Offers",
  "vehicle.bankComparison": "Bank Comparison",
  "vehicle.bestRate": "Best Rate",
  "vehicle.annualRate": "annual rate",
  "vehicle.totalInterestShort": "Interest:",
  "vehicle.savingsRange": "Savings Difference",
  // Finance
  "finance.badge": "Vehicle Financing",
  "finance.title": "Best",
  "finance.titleHighlight": "Car Loans",
  "finance.subtitle": "Compare car loan offers from Turkey's leading banks and discover the best interest rates.",
  "finance.banks": "Banks",
  "finance.minRate": "Lowest Rate",
  "finance.maxTerm": "Month Term",
  "finance.maxAmount": "Up to TRY",
  "finance.calculator": "Loan Calculator",
  "finance.loanAmount": "Loan Amount",
  "finance.loanTerm": "Term",
  "finance.months": "Months",
  "finance.loanType": "Loan Type",
  "finance.allTypes": "All Loans",
  "finance.vehicleLoan": "Car Loan",
  "finance.consumerLoan": "Personal Loan",
  "finance.searchBank": "Search bank...",
  "finance.sortByRate": "Lowest Rate",
  "finance.sortByRating": "Highest Rating",
  "finance.sortByAmount": "Highest Limit",
  "finance.interestRate": "Interest Rate",
  "finance.monthlyPayment": "Monthly Payment",
  "finance.totalInterest": "Total Interest",
  "finance.totalPayment": "Total Payment",
  "finance.specialOffer": "Special Offer",
  "finance.apply": "Apply",
  "finance.noResults": "No loans found matching your criteria.",
  "finance.lowRates": "Low Interest Rates",
  "finance.lowRatesDesc": "Compare the best interest rates in the market to find the option that fits your budget.",
  "finance.flexibleTerms": "Flexible Terms",
  "finance.flexibleTermsDesc": "Choose your payment plan with flexible term options from 12 to 60 months.",
  "finance.secure": "Secure Application",
  "finance.secureDesc": "All banks are BRSA licensed. Your information is securely protected.",
  "specs.engine": "Engine",
  "specs.power": "Power",
  "specs.fuel": "Fuel",
  "specs.fuelType": "Fuel Type",
  "specs.transmission": "Transmission",
  "specs.acceleration": "Acceleration",
  "specs.topSpeed": "Top Speed",
  "specs.fuelConsumption": "Fuel Consumption",
  "specs.bodyType": "Body Type",
  "vehicleList.title": "Vehicle Catalog",
  "vehicleList.subtitle": "+ vehicles to find the right one for you",
  "vehicleList.filters": "Filters",
  "vehicleList.allBrands": "All Brands",
  "vehicleList.allCategories": "All Categories",
  "vehicleList.allYears": "All Years",
  "vehicleList.sortPopular": "Most Popular",
  "vehicleList.sortRating": "Highest Rating",
  "vehicleList.sortReviews": "Most Reviews",
  "vehicleList.sortNewest": "Newest",
  "vehicleList.activeFilters": "Active Filters:",
  "vehicleList.clearAll": "Clear All",
  "vehicleList.clearFilters": "Clear Filters",
  "vehicleList.found": "vehicles found",
  "vehicleList.noResults": "No vehicles found matching your criteria.",
  "vehicleList.suggestVehicle": "Suggest Vehicle",
  "footer.description": "The world's most comprehensive premium and luxury car review platform. Real user experiences of 2022-2026 model premium vehicles.",
  "footer.quickLinks": "Quick Links",
  "footer.allVehicles": "All Vehicles",
  "footer.brands": "Brands",
  "footer.compareVehicles": "Compare Vehicles",
  "footer.mostPopular": "Most Popular",
  "footer.newModels": "New Models",
  "footer.categories": "Categories",
  "footer.contact": "Contact",
  "footer.rights": "All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Use",
  "category.sedan": "Sedan",
  "category.suv": "SUV",
  "category.hatchback": "Hatchback",
  "category.coupe": "Coupe",
  "category.pickup": "Pickup",
  "category.mpv": "MPV",
  "common.year": "Year",
  "common.category": "Category",
  "common.price": "Price",
  "common.rating": "Rating",
  "common.reviews": "Reviews",
  "common.error": "Error",
  "common.success": "Success",
  "common.loading": "Loading...",
  "profile.loading": "Loading...",
  "profile.loginRequired": "You must login to view the profile page.",
  "profile.editProfile": "Edit Profile",
  "profile.logout": "Logout",
  "profile.vehicleEnthusiast": "Vehicle Enthusiast",
  "profile.memberSince": "member since",
  "profile.reviews": "Reviews",
  "profile.likes": "Likes",
  "profile.followers": "Followers",
  "profile.editTitle": "Edit Profile",
  "profile.editDesc": "Update your profile information. Changes will appear on your profile after saving.",
  "profile.displayName": "Display Name",
  "profile.displayNameHint": "The name other users will see",
  "profile.displayNamePlaceholder": "Your Name",
  "profile.about": "About",
  "profile.aboutPlaceholder": "Introduce yourself briefly...",
  "profile.aboutHint": "Maximum 200 characters",
  "profile.location": "Location",
  "profile.locationPlaceholder": "City, Country",
  "profile.locationHint": "E.g: New York, USA",
  "profile.cancel": "Cancel",
  "profile.save": "Save",
  "profile.myReviews": "My Reviews",
  "profile.favorites": "Favorites",
  "profile.activity": "Activity",
  "profile.replies": "Replies",
  "profile.view": "View",
  "profile.detailedStats": "Detailed Statistics",
  "profile.totalReviews": "Total Reviews",
  "profile.thisMonth": "This month",
  "profile.averageRating": "Average Rating",
  "profile.totalLikes": "Total Likes",
  "profile.brandsExperienced": "Brands Experienced",
  "profile.diversity": "Diversity",
  "profile.achievements": "Achievements",
  "profile.earned": "Earned",
  "profile.progress": "Progress",
  "profile.reviewCategories": "Review Categories",
  "profile.brandDistribution": "Brand Distribution",
  "profile.ratingDistribution": "Rating Distribution",
  "profile.recentInteractions": "Recent Interactions",
  "profile.other": "Other",
  "profile.avatarSuccess": "Profile photo updated successfully!",
  "profile.avatarError": "Error uploading photo",
  "profile.profileSuccess": "Profile updated successfully!",
  "profile.profileError": "Error updating profile",
  "profile.fileTypeError": "Only JPG, PNG, WebP or GIF formats are supported.",
  "profile.fileSizeError": "File size must be maximum 5MB.",
};

// Chinese translations
const zhTranslations: Record<string, string> = {
  "nav.home": "首页",
  "nav.vehicles": "车辆",
  "nav.reviews": "评论",
  "nav.compare": "比较",
  "nav.communities": "社区",
  "auth.login": "登录",
  "auth.logout": "退出",
  "auth.profile": "我的资料",
  "auth.user": "用户",
  "auth.welcome": "欢迎",
  "auth.createAccount": "创建账户",
  "auth.loginDesc": "登录以继续",
  "auth.signupDesc": "注册以撰写评论和保存收藏",
  "auth.googleLogin": "使用Google登录",
  "auth.googleSignup": "使用Google注册",
  "auth.or": "或",
  "auth.email": "电子邮件",
  "auth.password": "密码",
  "auth.confirmPassword": "确认密码",
  "auth.signup": "注册",
  "auth.noAccount": "没有账户？",
  "auth.hasAccount": "已有账户？",
  "auth.backToHome": "返回首页",
  "auth.shareExperience": "分享您的车辆体验",
  "auth.shareDesc": "与数千用户一起撰写真实的车辆评论，保存您的收藏并与社区互动。",
  "premium.badge": "高级会员",
  "premium.button": "成为高级会员",
  "premium.member": "高级会员",
  "search.placeholder": "搜索品牌或型号...",
  "search.title": "站内搜索",
  "search.hint": "输入品牌或型号进行搜索",
  "search.noResults": "未找到结果",
  "search.mobile": "搜索...",
  "search.searchBrandModel": "搜索品牌、型号或类别...",
  "search.button": "搜索",
  "hero.badge": "世界#1车辆评论平台",
  "hero.title": "找到您的梦想",
  "hero.titleHighlight": "车辆",
  "hero.subtitle": "通过真实用户评论、详细评测和比较选择合适的车辆。",
  "stats.vehicles": "车型",
  "stats.reviews": "用户评论",
  "stats.brands": "品牌",
  "section.popularBrands": "热门品牌",
  "section.viewAll": "查看全部",
  "section.categories": "类别",
  "section.popularVehicles": "热门车辆",
  "section.popularVehiclesDesc": "评论最多、最受欢迎的车型",
  "section.latestReviews": "最新评论",
  "section.latestReviewsDesc": "用户最新评论",
  "section.readMore": "阅读更多 →",
  "cta.title": "分享您的体验",
  "cta.subtitle": "通过评论您的车辆来帮助其他用户并加入我们的社区。",
  "cta.button": "撰写评论",
  "review.writeTitle": "想撰写评论吗？",
  "review.writeDesc": "要分享您的体验，您需要先选择一辆车。您可以从车辆列表中选择您想评论的车辆。",
  "review.goToList": "前往车辆列表",
  "review.hint": "您可以通过点击车辆详情页面上的「撰写评论」按钮来分享您的体验。",
  "review.pros": "优点",
  "review.cons": "缺点",
  "review.helpful": "有帮助",
  "review.viewVehicle": "查看车辆",
  "review.reviews": "条评论",
  "vehicle.startingPrice": "起步价",
  "vehicle.review": "条评论",
  "vehicle.reviews": "条评论",
  "vehicle.notFound": "未找到车辆",
  "vehicle.backToVehicles": "返回车辆列表",
  "vehicle.model": "型号",
  "vehicle.evaluation": "条评价",
  "vehicle.writeReview": "撰写评论",
  "vehicle.specs": "规格",
  "vehicle.reviews.tab": "评论",
  "vehicle.overview": "概述",
  "vehicle.featuredFeatures": "特色功能",
  "vehicle.technicalSpecs": "技术规格",
  "vehicle.userReviews": "用户评论",
  "vehicle.noReviews": "暂无评论。成为第一个评论者！",
  "vehicle.writeFirstReview": "撰写第一条评论",
  "vehicle.reviewStats": "评论统计",
  "vehicle.totalReviews": "总评论数",
  "vehicle.averageRating": "平均评分",
  "vehicle.loginToReview": "登录后撰写评论",
  "vehicle.similarVehicles": "相似车辆",
  "specs.engine": "发动机",
  "specs.power": "功率",
  "specs.fuel": "燃油",
  "specs.fuelType": "燃油类型",
  "specs.transmission": "变速箱",
  "specs.acceleration": "加速",
  "specs.topSpeed": "最高速度",
  "specs.fuelConsumption": "油耗",
  "specs.bodyType": "车身类型",
  "vehicleList.title": "车辆目录",
  "vehicleList.subtitle": "+ 辆车可供选择",
  "vehicleList.filters": "筛选",
  "vehicleList.allBrands": "所有品牌",
  "vehicleList.allCategories": "所有类别",
  "vehicleList.allYears": "所有年份",
  "vehicleList.sortPopular": "最受欢迎",
  "vehicleList.sortRating": "最高评分",
  "vehicleList.sortReviews": "最多评论",
  "vehicleList.sortNewest": "最新",
  "vehicleList.activeFilters": "当前筛选：",
  "vehicleList.clearAll": "清除全部",
  "vehicleList.clearFilters": "清除筛选",
  "vehicleList.found": "辆车",
  "vehicleList.noResults": "未找到符合条件的车辆。",
  "vehicleList.suggestVehicle": "推荐车辆",
  "footer.description": "世界最全面的车辆评论平台。通过真实用户体验选择合适的车辆。",
  "footer.quickLinks": "快速链接",
  "footer.allVehicles": "所有车辆",
  "footer.brands": "品牌",
  "footer.compareVehicles": "比较车辆",
  "footer.mostPopular": "最受欢迎",
  "footer.newModels": "新车型",
  "footer.categories": "类别",
  "footer.contact": "联系我们",
  "footer.rights": "版权所有。",
  "footer.privacy": "隐私政策",
  "footer.terms": "使用条款",
  "category.sedan": "轿车",
  "category.suv": "SUV",
  "category.hatchback": "掀背车",
  "category.coupe": "跑车",
  "category.pickup": "皮卡",
  "category.mpv": "MPV",
  "common.year": "年份",
  "common.category": "类别",
  "common.price": "价格",
  "common.rating": "评分",
  "common.reviews": "评论",
  "common.error": "错误",
  "common.success": "成功",
  "common.loading": "加载中...",
  "profile.loading": "加载中...",
  "profile.loginRequired": "您必须登录才能查看个人资料页面。",
  "profile.editProfile": "编辑资料",
  "profile.logout": "退出登录",
  "profile.vehicleEnthusiast": "汽车爱好者",
  "profile.memberSince": "成为会员",
  "profile.reviews": "评论",
  "profile.likes": "点赞",
  "profile.followers": "粉丝",
  "profile.editTitle": "编辑资料",
  "profile.editDesc": "更新您的个人资料信息。保存后更改将显示在您的个人资料中。",
  "profile.displayName": "显示名称",
  "profile.displayNameHint": "其他用户将看到的名称",
  "profile.displayNamePlaceholder": "您的姓名",
  "profile.about": "关于",
  "profile.aboutPlaceholder": "简单介绍一下自己...",
  "profile.aboutHint": "最多200个字符",
  "profile.location": "位置",
  "profile.locationPlaceholder": "城市，国家",
  "profile.locationHint": "例如：北京，中国",
  "profile.cancel": "取消",
  "profile.save": "保存",
  "profile.myReviews": "我的评论",
  "profile.favorites": "收藏",
  "profile.activity": "活动",
  "profile.replies": "回复",
  "profile.view": "查看",
  "profile.detailedStats": "详细统计",
  "profile.totalReviews": "总评论数",
  "profile.thisMonth": "本月",
  "profile.averageRating": "平均评分",
  "profile.totalLikes": "总点赞数",
  "profile.brandsExperienced": "体验过的品牌",
  "profile.diversity": "多样性",
  "profile.achievements": "成就",
  "profile.earned": "已获得",
  "profile.progress": "进度",
  "profile.reviewCategories": "评论类别",
  "profile.brandDistribution": "品牌分布",
  "profile.ratingDistribution": "评分分布",
  "profile.recentInteractions": "最近互动",
  "profile.other": "其他",
  "profile.avatarSuccess": "头像更新成功！",
  "profile.avatarError": "上传照片时出错",
  "profile.profileSuccess": "个人资料更新成功！",
  "profile.profileError": "更新个人资料时出错",
  "profile.fileTypeError": "仅支持JPG、PNG、WebP或GIF格式。",
  "profile.fileSizeError": "文件大小不能超过5MB。",
};

// Spanish translations
const esTranslations: Record<string, string> = {
  "nav.home": "Inicio",
  "nav.vehicles": "Vehículos",
  "nav.reviews": "Reseñas",
  "nav.compare": "Comparar",
  "nav.communities": "Comunidades",
  "auth.login": "Iniciar sesión",
  "auth.logout": "Cerrar sesión",
  "auth.profile": "Mi Perfil",
  "auth.user": "Usuario",
  "auth.welcome": "Bienvenido",
  "auth.createAccount": "Crear Cuenta",
  "auth.loginDesc": "Inicia sesión para continuar",
  "auth.signupDesc": "Regístrate para escribir reseñas y guardar favoritos",
  "auth.googleLogin": "Iniciar con Google",
  "auth.googleSignup": "Registrarse con Google",
  "auth.or": "o",
  "auth.email": "Correo electrónico",
  "auth.password": "Contraseña",
  "auth.confirmPassword": "Confirmar Contraseña",
  "auth.signup": "Registrarse",
  "auth.noAccount": "¿No tienes cuenta?",
  "auth.hasAccount": "¿Ya tienes cuenta?",
  "auth.backToHome": "Volver al Inicio",
  "auth.shareExperience": "Comparte Tu Experiencia con Vehículos",
  "auth.shareDesc": "Escribe reseñas reales con miles de usuarios, guarda tus favoritos e interactúa con la comunidad.",
  "premium.badge": "Premium",
  "premium.button": "Ser Premium",
  "premium.member": "Miembro Premium",
  "search.placeholder": "Buscar marca o modelo...",
  "search.title": "Búsqueda del sitio",
  "search.hint": "Escribe marca o modelo para buscar",
  "search.noResults": "No se encontraron resultados para",
  "search.mobile": "Buscar...",
  "search.searchBrandModel": "Buscar marca, modelo o categoría...",
  "search.button": "Buscar",
  "hero.badge": "Plataforma #1 de Reseñas de Vehículos del Mundo",
  "hero.title": "Encuentra Tu",
  "hero.titleHighlight": "Vehículo Soñado",
  "hero.subtitle": "Elige el vehículo correcto con reseñas reales, análisis detallados y comparaciones.",
  "stats.vehicles": "Modelos de Vehículos",
  "stats.reviews": "Reseñas de Usuarios",
  "stats.brands": "Marcas",
  "section.popularBrands": "Marcas Populares",
  "section.viewAll": "Ver Todo",
  "section.categories": "Categorías",
  "section.popularVehicles": "Vehículos Populares",
  "section.popularVehiclesDesc": "Los modelos más reseñados y gustados",
  "section.latestReviews": "Últimas Reseñas",
  "section.latestReviewsDesc": "Las reseñas más recientes de los usuarios",
  "section.readMore": "Leer más →",
  "cta.title": "Comparte Tu Experiencia",
  "cta.subtitle": "Ayuda a otros usuarios reseñando tu vehículo y únete a nuestra comunidad.",
  "cta.button": "Escribir Reseña",
  "review.writeTitle": "¿Quieres Escribir una Reseña?",
  "review.writeDesc": "Para compartir tu experiencia, primero debes seleccionar un vehículo de la lista.",
  "review.goToList": "Ir a Lista de Vehículos",
  "review.hint": "Puedes compartir tu experiencia haciendo clic en el botón \"Escribir Reseña\" en la página de detalles del vehículo.",
  "review.pros": "Pros",
  "review.cons": "Contras",
  "review.helpful": "Útil",
  "review.viewVehicle": "Ver Vehículo",
  "review.reviews": "reseñas",
  "vehicle.startingPrice": "Precio Inicial",
  "vehicle.review": "reseña",
  "vehicle.reviews": "reseñas",
  "vehicle.notFound": "Vehículo no encontrado",
  "vehicle.backToVehicles": "Volver a Vehículos",
  "vehicle.model": "Modelo",
  "vehicle.evaluation": "reseñas",
  "vehicle.writeReview": "Escribir Reseña",
  "vehicle.specs": "Especificaciones",
  "vehicle.reviews.tab": "Reseñas",
  "vehicle.overview": "Descripción",
  "vehicle.featuredFeatures": "Características Destacadas",
  "vehicle.technicalSpecs": "Especificaciones Técnicas",
  "vehicle.userReviews": "Reseñas de Usuarios",
  "vehicle.noReviews": "Aún no hay reseñas. ¡Sé el primero en opinar!",
  "vehicle.writeFirstReview": "Escribir Primera Reseña",
  "vehicle.reviewStats": "Estadísticas de Reseñas",
  "vehicle.totalReviews": "Total de Reseñas",
  "vehicle.averageRating": "Calificación Promedio",
  "vehicle.loginToReview": "Inicia sesión para escribir una reseña",
  "vehicle.similarVehicles": "Vehículos Similares",
  "specs.engine": "Motor",
  "specs.power": "Potencia",
  "specs.fuel": "Combustible",
  "specs.fuelType": "Tipo de Combustible",
  "specs.transmission": "Transmisión",
  "specs.acceleration": "Aceleración",
  "specs.topSpeed": "Velocidad Máxima",
  "specs.fuelConsumption": "Consumo",
  "specs.bodyType": "Tipo de Carrocería",
  "vehicleList.title": "Catálogo de Vehículos",
  "vehicleList.subtitle": "+ vehículos para encontrar el adecuado para ti",
  "vehicleList.filters": "Filtros",
  "vehicleList.allBrands": "Todas las Marcas",
  "vehicleList.allCategories": "Todas las Categorías",
  "vehicleList.allYears": "Todos los Años",
  "vehicleList.sortPopular": "Más Popular",
  "vehicleList.sortRating": "Mayor Calificación",
  "vehicleList.sortReviews": "Más Reseñas",
  "vehicleList.sortNewest": "Más Nuevo",
  "vehicleList.activeFilters": "Filtros Activos:",
  "vehicleList.clearAll": "Limpiar Todo",
  "vehicleList.clearFilters": "Limpiar Filtros",
  "vehicleList.found": "vehículos encontrados",
  "vehicleList.noResults": "No se encontraron vehículos que coincidan.",
  "vehicleList.suggestVehicle": "Sugerir Vehículo",
  "footer.description": "La plataforma de reseñas de vehículos más completa del mundo.",
  "footer.quickLinks": "Enlaces Rápidos",
  "footer.allVehicles": "Todos los Vehículos",
  "footer.brands": "Marcas",
  "footer.compareVehicles": "Comparar Vehículos",
  "footer.mostPopular": "Más Popular",
  "footer.newModels": "Nuevos Modelos",
  "footer.categories": "Categorías",
  "footer.contact": "Contacto",
  "footer.rights": "Todos los derechos reservados.",
  "footer.privacy": "Política de Privacidad",
  "footer.terms": "Términos de Uso",
  "category.sedan": "Sedán",
  "category.suv": "SUV",
  "category.hatchback": "Hatchback",
  "category.coupe": "Coupé",
  "category.pickup": "Pickup",
  "category.mpv": "MPV",
  "common.year": "Año",
  "common.category": "Categoría",
  "common.price": "Precio",
  "common.rating": "Calificación",
  "common.reviews": "Reseñas",
  "common.error": "Error",
  "common.success": "Éxito",
  "common.loading": "Cargando...",
  "profile.loading": "Cargando...",
  "profile.loginRequired": "Debes iniciar sesión para ver la página de perfil.",
  "profile.editProfile": "Editar Perfil",
  "profile.logout": "Cerrar Sesión",
  "profile.vehicleEnthusiast": "Entusiasta de Vehículos",
  "profile.memberSince": "miembro desde",
  "profile.reviews": "Reseñas",
  "profile.likes": "Me gusta",
  "profile.followers": "Seguidores",
  "profile.editTitle": "Editar Perfil",
  "profile.editDesc": "Actualiza tu información de perfil. Los cambios aparecerán en tu perfil después de guardar.",
  "profile.displayName": "Nombre para Mostrar",
  "profile.displayNameHint": "El nombre que verán otros usuarios",
  "profile.displayNamePlaceholder": "Tu Nombre",
  "profile.about": "Acerca de",
  "profile.aboutPlaceholder": "Preséntate brevemente...",
  "profile.aboutHint": "Máximo 200 caracteres",
  "profile.location": "Ubicación",
  "profile.locationPlaceholder": "Ciudad, País",
  "profile.locationHint": "Ej: Madrid, España",
  "profile.cancel": "Cancelar",
  "profile.save": "Guardar",
  "profile.myReviews": "Mis Reseñas",
  "profile.favorites": "Favoritos",
  "profile.activity": "Actividad",
  "profile.replies": "Respuestas",
  "profile.view": "Ver",
  "profile.detailedStats": "Estadísticas Detalladas",
  "profile.totalReviews": "Total de Reseñas",
  "profile.thisMonth": "Este mes",
  "profile.averageRating": "Calificación Promedio",
  "profile.totalLikes": "Total Me Gusta",
  "profile.brandsExperienced": "Marcas Experimentadas",
  "profile.diversity": "Diversidad",
  "profile.achievements": "Logros",
  "profile.earned": "Obtenido",
  "profile.progress": "Progreso",
  "profile.reviewCategories": "Categorías de Reseñas",
  "profile.brandDistribution": "Distribución de Marcas",
  "profile.ratingDistribution": "Distribución de Calificaciones",
  "profile.recentInteractions": "Interacciones Recientes",
  "profile.other": "Otro",
  "profile.avatarSuccess": "¡Foto de perfil actualizada!",
  "profile.avatarError": "Error al subir la foto",
  "profile.profileSuccess": "¡Perfil actualizado!",
  "profile.profileError": "Error al actualizar el perfil",
  "profile.fileTypeError": "Solo se admiten formatos JPG, PNG, WebP o GIF.",
  "profile.fileSizeError": "El tamaño del archivo debe ser máximo 5MB.",
};

// Use Turkish as base for other languages (fallback)
const createTranslations = (overrides: Partial<Record<string, string>>): Record<string, string> => ({
  ...trTranslations,
  ...overrides,
});

function getTranslations(lang: LanguageCode): Record<string, string> {
  const translations: Record<LanguageCode, Record<string, string>> = {
    tr: trTranslations,
    en: enTranslations,
    zh: zhTranslations,
    es: esTranslations,
    // For other languages, use Turkish as base with key adjustments
    hi: createTranslations({
      "nav.home": "होम", "nav.vehicles": "वाहन", "nav.reviews": "समीक्षाएं", "nav.compare": "तुलना करें", "nav.communities": "समुदाय",
      "auth.login": "लॉगिन", "auth.logout": "लॉगआउट", "auth.profile": "मेरी प्रोफाइल",
      "premium.badge": "प्रीमियम", "premium.button": "प्रीमियम बनें", "premium.member": "प्रीमियम सदस्य",
      "search.placeholder": "ब्रांड या मॉडल खोजें...", "search.button": "खोजें",
      "hero.badge": "विश्व का #1 वाहन समीक्षा प्लेटफ़ॉर्म",
      "hero.title": "अपनी सपनों की", "hero.titleHighlight": "कार खोजें",
      "section.viewAll": "सभी देखें", "section.categories": "श्रेणियां",
      "footer.description": "विश्व का सबसे व्यापक वाहन समीक्षा प्लेटफ़ॉर्म।",
      "footer.rights": "सर्वाधिकार सुरक्षित।",
      "vehicle.startingPrice": "शुरुआती कीमत",
      "review.helpful": "सहायक", "review.reviews": "समीक्षाएं", "review.pros": "फायदे", "review.cons": "नुकसान",
    }),
    ar: createTranslations({
      "nav.home": "الرئيسية", "nav.vehicles": "المركبات", "nav.reviews": "المراجعات", "nav.compare": "مقارنة", "nav.communities": "المجتمعات",
      "auth.login": "تسجيل الدخول", "auth.logout": "تسجيل الخروج", "auth.profile": "ملفي",
      "premium.badge": "بريميوم", "premium.button": "كن بريميوم", "premium.member": "عضو بريميوم",
      "search.placeholder": "ابحث عن علامة أو طراز...", "search.button": "بحث",
      "hero.badge": "منصة مراجعة المركبات رقم 1 في العالم",
      "hero.title": "اعثر على سيارة", "hero.titleHighlight": "أحلامك",
      "section.viewAll": "عرض الكل", "section.categories": "الفئات",
      "footer.description": "أشمل منصة لمراجعة المركبات في العالم.",
      "footer.rights": "جميع الحقوق محفوظة.",
      "vehicle.startingPrice": "السعر الابتدائي",
      "review.helpful": "مفيد", "review.reviews": "مراجعات", "review.pros": "المميزات", "review.cons": "العيوب",
    }),
    bn: createTranslations({
      "nav.home": "হোম", "nav.vehicles": "যানবাহন", "nav.reviews": "পর্যালোচনা", "nav.compare": "তুলনা করুন", "nav.communities": "সম্প্রদায়",
      "auth.login": "লগইন", "auth.logout": "লগআউট", "auth.profile": "আমার প্রোফাইল",
      "premium.badge": "প্রিমিয়াম", "premium.button": "প্রিমিয়াম হন", "premium.member": "প্রিমিয়াম সদস্য",
      "search.placeholder": "ব্র্যান্ড বা মডেল খুঁজুন...", "search.button": "অনুসন্ধান",
      "hero.badge": "বিশ্বের #১ গাড়ি পর্যালোচনা প্ল্যাটফর্ম",
      "section.viewAll": "সব দেখুন", "section.categories": "বিভাগ",
      "footer.description": "বিশ্বের সবচেয়ে ব্যাপক গাড়ি পর্যালোচনা প্ল্যাটফর্ম।",
      "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
      "vehicle.startingPrice": "শুরুর মূল্য",
      "review.helpful": "সহায়ক", "review.reviews": "পর্যালোচনা", "review.pros": "সুবিধা", "review.cons": "অসুবিধা",
    }),
    pt: createTranslations({
      "nav.home": "Início", "nav.vehicles": "Veículos", "nav.reviews": "Avaliações", "nav.compare": "Comparar", "nav.communities": "Comunidades",
      "auth.login": "Entrar", "auth.logout": "Sair", "auth.profile": "Meu Perfil",
      "premium.badge": "Premium", "premium.button": "Seja Premium", "premium.member": "Membro Premium",
      "search.placeholder": "Pesquisar marca ou modelo...", "search.button": "Pesquisar",
      "hero.badge": "Plataforma #1 de Avaliação de Veículos do Mundo",
      "hero.title": "Encontre Seu", "hero.titleHighlight": "Carro dos Sonhos",
      "section.viewAll": "Ver Tudo", "section.categories": "Categorias",
      "footer.description": "A plataforma de avaliação de veículos mais completa do mundo.",
      "footer.rights": "Todos os direitos reservados.",
      "vehicle.startingPrice": "Preço Inicial",
      "review.helpful": "Útil", "review.reviews": "avaliações", "review.pros": "Prós", "review.cons": "Contras",
    }),
    ru: createTranslations({
      "nav.home": "Главная", "nav.vehicles": "Автомобили", "nav.reviews": "Обзоры", "nav.compare": "Сравнить", "nav.communities": "Сообщества",
      "auth.login": "Войти", "auth.logout": "Выйти", "auth.profile": "Мой профиль",
      "premium.badge": "Премиум", "premium.button": "Стать Премиум", "premium.member": "Премиум участник",
      "search.placeholder": "Поиск марки или модели...", "search.button": "Поиск",
      "hero.badge": "Платформа #1 для обзоров автомобилей в мире",
      "hero.title": "Найдите Свой", "hero.titleHighlight": "Автомобиль Мечты",
      "section.viewAll": "Смотреть все", "section.categories": "Категории",
      "footer.description": "Самая полная платформа для обзоров автомобилей в мире.",
      "footer.rights": "Все права защищены.",
      "vehicle.startingPrice": "Начальная цена",
      "review.helpful": "Полезно", "review.reviews": "отзывов", "review.pros": "Плюсы", "review.cons": "Минусы",
    }),
    ja: createTranslations({
      "nav.home": "ホーム", "nav.vehicles": "車両", "nav.reviews": "レビュー", "nav.compare": "比較", "nav.communities": "コミュニティ",
      "auth.login": "ログイン", "auth.logout": "ログアウト", "auth.profile": "マイプロフィール",
      "premium.badge": "プレミアム", "premium.button": "プレミアムになる", "premium.member": "プレミアム会員",
      "search.placeholder": "ブランドまたはモデルを検索...", "search.button": "検索",
      "hero.badge": "世界No.1の車両レビュープラットフォーム",
      "hero.title": "夢の車を", "hero.titleHighlight": "見つけよう",
      "section.viewAll": "すべて見る", "section.categories": "カテゴリ",
      "footer.description": "世界で最も包括的な車両レビュープラットフォーム。",
      "footer.rights": "無断転載禁止。",
      "vehicle.startingPrice": "開始価格",
      "review.helpful": "役に立った", "review.reviews": "件のレビュー", "review.pros": "良い点", "review.cons": "悪い点",
    }),
    de: createTranslations({
      "nav.home": "Startseite", "nav.vehicles": "Fahrzeuge", "nav.reviews": "Bewertungen", "nav.compare": "Vergleichen", "nav.communities": "Gemeinschaften",
      "auth.login": "Anmelden", "auth.logout": "Abmelden", "auth.profile": "Mein Profil",
      "premium.badge": "Premium", "premium.button": "Premium werden", "premium.member": "Premium-Mitglied",
      "search.placeholder": "Marke oder Modell suchen...", "search.button": "Suchen",
      "hero.badge": "Die #1 Fahrzeugbewertungsplattform der Welt",
      "hero.title": "Finden Sie Ihr", "hero.titleHighlight": "Traumauto",
      "section.viewAll": "Alle anzeigen", "section.categories": "Kategorien",
      "footer.description": "Die umfassendste Fahrzeugbewertungsplattform der Welt.",
      "footer.rights": "Alle Rechte vorbehalten.",
      "vehicle.startingPrice": "Startpreis",
      "review.helpful": "Hilfreich", "review.reviews": "Bewertungen", "review.pros": "Vorteile", "review.cons": "Nachteile",
    }),
    fr: createTranslations({
      "nav.home": "Accueil", "nav.vehicles": "Véhicules", "nav.reviews": "Avis", "nav.compare": "Comparer", "nav.communities": "Communautés",
      "auth.login": "Connexion", "auth.logout": "Déconnexion", "auth.profile": "Mon Profil",
      "premium.badge": "Premium", "premium.button": "Devenir Premium", "premium.member": "Membre Premium",
      "search.placeholder": "Rechercher marque ou modèle...", "search.button": "Rechercher",
      "hero.badge": "La plateforme #1 d'avis sur les véhicules au monde",
      "hero.title": "Trouvez Votre", "hero.titleHighlight": "Véhicule de Rêve",
      "section.viewAll": "Voir Tout", "section.categories": "Catégories",
      "footer.description": "La plateforme d'avis sur les véhicules la plus complète au monde.",
      "footer.rights": "Tous droits réservés.",
      "vehicle.startingPrice": "Prix de départ",
      "review.helpful": "Utile", "review.reviews": "avis", "review.pros": "Avantages", "review.cons": "Inconvénients",
    }),
    ko: createTranslations({
      "nav.home": "홈", "nav.vehicles": "차량", "nav.reviews": "리뷰", "nav.compare": "비교", "nav.communities": "커뮤니티",
      "auth.login": "로그인", "auth.logout": "로그아웃", "auth.profile": "내 프로필",
      "premium.badge": "프리미엄", "premium.button": "프리미엄 되기", "premium.member": "프리미엄 회원",
      "search.placeholder": "브랜드 또는 모델 검색...", "search.button": "검색",
      "hero.badge": "세계 최고의 차량 리뷰 플랫폼",
      "hero.title": "꿈의 자동차를", "hero.titleHighlight": "찾으세요",
      "section.viewAll": "모두 보기", "section.categories": "카테고리",
      "footer.description": "세계에서 가장 포괄적인 차량 리뷰 플랫폼.",
      "footer.rights": "모든 권리 보유.",
      "vehicle.startingPrice": "시작 가격",
      "review.helpful": "도움됨", "review.reviews": "개 리뷰", "review.pros": "장점", "review.cons": "단점",
    }),
    it: createTranslations({
      "nav.home": "Home", "nav.vehicles": "Veicoli", "nav.reviews": "Recensioni", "nav.compare": "Confronta", "nav.communities": "Comunità",
      "auth.login": "Accedi", "auth.logout": "Esci", "auth.profile": "Il Mio Profilo",
      "premium.badge": "Premium", "premium.button": "Diventa Premium", "premium.member": "Membro Premium",
      "search.placeholder": "Cerca marca o modello...", "search.button": "Cerca",
      "hero.badge": "La piattaforma #1 di recensioni veicoli al mondo",
      "hero.title": "Trova La Tua", "hero.titleHighlight": "Auto dei Sogni",
      "section.viewAll": "Vedi Tutto", "section.categories": "Categorie",
      "footer.description": "La piattaforma di recensioni veicoli più completa al mondo.",
      "footer.rights": "Tutti i diritti riservati.",
      "vehicle.startingPrice": "Prezzo di partenza",
      "review.helpful": "Utile", "review.reviews": "recensioni", "review.pros": "Pro", "review.cons": "Contro",
    }),
    vi: createTranslations({
      "nav.home": "Trang chủ", "nav.vehicles": "Xe", "nav.reviews": "Đánh giá", "nav.compare": "So sánh", "nav.communities": "Cộng đồng",
      "auth.login": "Đăng nhập", "auth.logout": "Đăng xuất", "auth.profile": "Hồ sơ của tôi",
      "premium.badge": "Premium", "premium.button": "Trở thành Premium", "premium.member": "Thành viên Premium",
      "search.placeholder": "Tìm thương hiệu hoặc model...", "search.button": "Tìm kiếm",
      "hero.badge": "Nền tảng đánh giá xe #1 thế giới",
      "hero.title": "Tìm Chiếc Xe", "hero.titleHighlight": "Mơ Ước",
      "section.viewAll": "Xem tất cả", "section.categories": "Danh mục",
      "footer.description": "Nền tảng đánh giá xe toàn diện nhất thế giới.",
      "footer.rights": "Đã đăng ký bản quyền.",
      "vehicle.startingPrice": "Giá khởi điểm",
      "review.helpful": "Hữu ích", "review.reviews": "đánh giá", "review.pros": "Ưu điểm", "review.cons": "Nhược điểm",
    }),
  };

  return translations[lang] || trTranslations;
}
